[SERVICE]
    Flush           1
    Daemon          Off
    Log_Level       info

    # parser.conf 파일의 JSON 규칙을 기반으로 파서 파일을 불러온다
    Parsers_File    parsers.conf
    
    # [유실 방지 1] 디스크 버퍼링 활성화
    storage.path    /tmp/flb-storage/
    storage.sync    normal
    storage.checksum off
    storage.backlog.mem_limit 5M

[INPUT]
    Name            tail
    # 수집할 실제 BPF 로그 파일 경로 (환경에 맞게 수정하세요)
    Path            /home/eBPF_Project/testdata/normalized.jsonl
    Tag             normalized.logs
    
    # 파서 적용
    Parser          json
    
    # [유실 방지 2] 어디까지 읽었는지 위치를 기억하는 DB 파일
    DB              /tmp/flb_ebpf.db
    
    # 메모리 버퍼 한도 설정
    Mem_Buf_Limit   10MB
    Skip_Long_Lines On

    # [추가!] 이미 있는 파일의 맨 첫 줄부터 읽기 시작합니다.
    Read_from_Head  On

# [분류] JSON 필드(event_type) 값에 따라 태그 분기 처리
[FILTER]
    Name            rewrite_tag
    Match           normalized.logs
    
    # -------------------------------------------------------------
    # [토픽 라우팅 규칙] 
    # 정규표현식에 매칭되면, 태그를 실제 "Kafka 토픽 이름"과 똑같이 바꿉니다.
    # -------------------------------------------------------------
    # Rule 작성법: $키 정규표현식 새_태그 원본유지여부(false로 해야 중복 안됨)

    # 1. 프로세스 이벤트 -> tetragon.process 토픽으로
    Rule            $event_type ^edr\.process\..* tetragon.process  false
    
    # 2. 네트워크 이벤트 -> tetragon.network 토픽으로
    Rule            $event_type ^edr\.network\..* tetragon.network  false
    
    # 3. 인증/권한 이벤트 -> tetragon.auth 토픽으로
    Rule            $event_type ^edr\.auth\..* tetragon.auth     false

    # 4. 파일 접근 이벤트 -> tetragon.file 토픽으로
    Rule            $event_type ^edr\.file\..* tetragon.file     false

    # 5. [수집기 기준 분류] Auditd 로그 -> auditd 토픽으로
    Rule            $collector['name'] ^auditd$    auditd            false

    # 6. [수집기 기준 분류] Journald 로그 -> journald 토픽으로
    Rule            $collector['name'] ^journald$  journald          false


# 3. 이후 OUTPUT에서 Match 값을 이용하여 각각 다른 토픽으로 전송합니다.
[OUTPUT]
    Name            kafka
    # 방금 위에서 이름표가 바뀐(라우팅된) 모든 태그를 한 번에 잡아냅니다.
    Match_Regex     ^(tetragon\..*|auditd|journald|network|sensor)$
    Brokers         54.162.40.179:9092
    
    # 🌟 [핵심] Topics 옵션을 일부러 생략 => 이로 인해 Fluent Bit가 "아, 태그 이름이랑 토픽 이름이랑 같구나!" 하고 판단 후 토픽으로 전송함

    Retry_Limit     False
