[PARSER]
    Name        json
    Format      json
    # 로그 파일 내의 eBPF 센서가 감지했던 원래의 정확한 시간(event_time)을 기준으로 설정
    Time_Key    event_time
    # 2026-03-21T07:42:46.136983134Z 형태의 시간을 파싱하기 위한 포맷
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z